name: Test-project

on:
  push:
    branches:
      - master
  workflow_dispatch:  # allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script and save output
        run: |
          python decorator.py > output.txt

      - name: Upload output file
        uses: actions/upload-artifact@v4
        with:
          name: script-output
          path: output.txt
